"""Log three SYNTHETIC retrain-style runs to a local MLflow server.

    # terminal 1: a throw-away local server (sqlite store, nothing leaves the machine)
    mlflow server --host 127.0.0.1 --port 5055 --backend-store-uri sqlite:///mlflow-demo.db
    # terminal 2:
    PINANCE_MLFLOW_TRACKING_URI=http://127.0.0.1:5055 python docs/examples/mlflow_demo.py

It reuses the repository's own tracking wrapper (`pinance_ml.tracking`) with
the same experiment name, parameter, metric and tag keys that
`scripts/auto_retrain.py` writes, so the MLflow screens look like the real
ones. The data are generated by `synthetic_walkforward_demo.py`; numbers
carry no information about any market. `candidate` and `production` here are
two LightGBM configurations trained on the same synthetic history.
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

if not os.environ.get("PINANCE_MLFLOW_TRACKING_URI"):
    sys.exit("set PINANCE_MLFLOW_TRACKING_URI, e.g. http://127.0.0.1:5055")

os.environ.setdefault("DATABASE_URL", "postgresql://unused/unused")
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parents[1] / "src"))

import numpy as np
import pandas as pd
from synthetic_walkforward_demo import synthetic_candles

from pinance_ml.config import HORIZONS
from pinance_ml.dataset import build_dataset, feature_columns
from pinance_ml.metrics import directional_accuracy, mae
from pinance_ml.models.lightgbm_model import predict_horizons, train_horizon_models
from pinance_ml.tracking import log_dict, log_metrics, log_params, mlflow_run, set_tags

HOLDOUT_DAYS = 14
CANDIDATE = {"n_estimators": 60, "num_leaves": 15, "min_child_samples": 200}
PRODUCTION = {"n_estimators": 30, "num_leaves": 7, "min_child_samples": 400}


def evaluate(models, frame, feats):
    preds = predict_horizons(models, frame, feats)
    maes = [mae(frame[f"r_{h}"], preds[f"r_{h}_pred"]) for h in HORIZONS]
    accs = [directional_accuracy(frame[f"r_{h}"], preds[f"r_{h}_pred"]) for h in HORIZONS]
    return float(np.mean(maes)), float(np.mean(accs))


def main() -> None:
    for seed, name in enumerate(["SYNTH-A", "SYNTH-B", "SYNTH-C"]):
        data = build_dataset(synthetic_candles(150, seed=seed))
        feats = feature_columns(data)
        cut = data["ts"].iloc[-1] - pd.Timedelta(days=HOLDOUT_DAYS)
        train = data[data["ts"] < cut - pd.Timedelta(minutes=5 * 12)]  # purge, as in the real script
        holdout = data[data["ts"] >= cut]
        t0 = time.time()
        cand = train_horizon_models(train, feats, params=CANDIDATE)
        wall = time.time() - t0
        prod = train_horizon_models(train, feats, params=PRODUCTION)
        c_mae, c_acc = evaluate(cand, holdout, feats)
        p_mae, p_acc = evaluate(prod, holdout, feats)
        improvement = (p_mae - c_mae) / p_mae
        decision = "pushed_to_candidate" if improvement >= 0.005 else "rejected"
        with mlflow_run("retrain-point", run_name=name, tags={"kind": "point", "data": "synthetic"}):
            log_params({"symbol": name, "holdout_days": HOLDOUT_DAYS, "min_improvement": 0.005,
                        "n_train_rows": len(train), "n_eval_rows": len(holdout), "n_features": len(feats)})
            log_metrics({"candidate_avg_mae": c_mae, "candidate_avg_dir_acc": c_acc, "production_avg_mae": p_mae,
                         "production_avg_dir_acc": p_acc, "improvement": improvement, "train_wall_seconds": wall})
            set_tags({"decision": decision, "target_slot": "candidate" if decision != "rejected" else "none"})
            log_dict({"decision": decision, "candidate_avg_mae": c_mae, "production_avg_mae": p_mae}, "eval_metrics.json")
        print(f"{name}: candidate MAE {c_mae:.6f} DA {c_acc:.4f} | production MAE {p_mae:.6f} DA {p_acc:.4f} | {decision}")


if __name__ == "__main__":
    main()
